version: "3"
services:
  node-app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - /app/node_modules
      - .:/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command:
      - "--smallfiles"
